### ISSUE TITLE
reducing color brightness in relative number with custom interval (maybe fibonacci)

### ISSUE THREAD

**Issue by chaitanyabsprip** [IMOKURI/line-number-interval.nvim#5]
Is there a way to make the color of the number in descending brightness as you go farther from the current cursor position. It would probably require multiple highlight groups. I'd really like to have this in my setup.

**Comment by IMOKURI** [comment]
Thank you for your comment. I'm interested in your idea.
I've implemented this idea.
Please check latest code.

**Comment by chaitanyabsprip** [comment]
is it possible without relative number?

**Comment by chaitanyabsprip** [comment]
maybe this comment can offer a solution, 
so instead of checking against the exact numbers present in the custom interval lists, you can check whether rnu is set or not, if it is, then consider the number mentioned in the custom interval list as exact but if rnu is not set then consider the number in the custom interval list as relative, offset from the current line (`vim.fn.line('.')`)

**Comment by IMOKURI** [comment]
OK, I've opened new issue for no relative number. #10

**Comment by chaitanyabsprip** [comment]
do you wish to port this to lua? I could help with that if this is something you are interested in

**Comment by IMOKURI** [comment]
I have currently no plan to port this plugin to lua.
